#!/bin/bash

help() {
   echo 'usage: renew-le-certificate'
   echo '       renew-le-certificate --help'
   echo
   echo '    Renew a Letsencrypt certificate on a Synology box,'
   echo '    that is behind a FRITZ!Box.'
   echo
   echo '    1. will open port 80 forwarding on a FRITZ!Box to'
   echo '       the Synology box'
   echo '    2. will renew the Letsencrypt certificate on the'
   echo '       Synology box'
   echo '    3. will disable the port 80 forwarding'
   echo
   echo '    This script (and if needed its config files) need'
   echo '    to be installed on and run from the Synology box'
   echo '    and the Synology box needs to be able to reach the'
   echo '    FRITZ!Box.'
   echo
   echo '     You can set the following variables directly in the'
   echo '     script, or in ~/.renew-le-certificate.conf :'
   echo
   echo '         SYNOLOGY=0.0.0.1'
   echo
   echo '     Also to see what Fritzbox settings you need to set'
   echo '     execute:'
   echo
   echo '         fritzbox-forward-port --help'
   echo
   echo '     NOTE: this script depends on the fritzbox-forward-port'
   echo '           script from https://github.com/tpo/fritzbox-forward-port'
   echo
   exit 0
}

# replace as adequate or...
#
SYNOLOGY=0.0.0.1

# ... set it in ~/.renew-le-certificate.conf
# make sure ~/.renew-le-certificate.conf is rwx------
#
[ -f ~/.renew-le-certificate.conf ] && source ~/.renew-le-certificate.conf

# * LE Renewal on Syno
#   https://www.synology-forum.de/threads/automatisierte-lets-encrypt-erneuerung-inkl-portfreigabe-fritz-box-integration.106559/post-860429

[ "$1" == "--help" ] && help

enable_port_80_forwarding_to_synology() {
  fritzbox-forward-port ENABLE "$SYNOLOGY" 80 "HTTP to Synology"
}

# I could not get DeletePortMapping to work
#
disable_port_80_forwarding_to_synology() {
  fritzbox-forward-port DISABLE "$SYNOLOGY" 80 "HTTP to Synology"
}

if enable_port_80_forwarding_to_synology; then
  /usr/syno/sbin/syno-letsencrypt renew-all -vv
  status=$?
fi

disable_port_80_forwarding_to_synology

if [ "$status" == "0" ]; then
  echo "success :-)"
  exit 0
else
  echo "failed"
  exit 1
fi
